### ISSUE TITLE
User customizable screens

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#16]
https://github.com/mr-kenhoff/qalculate-android/issues/15#issuecomment-1080036269

> I was also thinking about user-customizable screens. In this case, there needs to be some kind of button library, and a layout editor. However, I do not know if many users would actually use such a feature. A few well designed screens for different applications / complexities might come in more handy...

**Comment by ByteHamster** [comment]
While a layout editor would be kind of cool, I think we should aim for static, well designed screens first. That's what most users will use. (Also, doing everything else will be enough work already :D)

**Comment by ByteHamster** [comment]
I guess this is no longer planned and can be closed, now that you removed the layout parsing when redesigning?

**Comment by jherkenhoff** [comment]
Still not sure (like you also pointed out in your previous comment) if a layout editor would actually be used. I removed the layout parsing during the jetpack-compose rewrite just because it was easier, but I think we might go with constant layouts for now and add user customizability later if its needed.
