### ISSUE TITLE
Consider making it crossplatform

### ISSUE THREAD

**Issue by utkarshsethi** [jherkenhoff/qalculate-android#35]
expanding on #18.

Android and iOS both lack decent calculators which can compete with my casio.

Having it on my phone/tab can make life a lot better.
While I use Android as my phone, I use an iPad as a tablet, and the lack of a calculator which is remotely decent is baffling.

Since you mention you are still in early dev, would you consider building it cross-platform from the get-go?

**Comment by jherkenhoff** [comment]
Hi @utkarshsethi,

thanks for your suggestion.
I also initially thought about using a framework like react native or flutter to make the GUI cross platform. However, the library (libqalculate) still needs to be compiled for the native platform.
Also, since I do not own a Mac or any apple device I am unfortunately not able to do any development in that direction.

**Comment by jherkenhoff** [comment]
Hi @utkarshsethi 
unfortunately, porting this App to ios is very hard to impossible, since it makes use of a lot of very android specific implementation details (like jetpack compose).
The underlying library https://github.com/jherkenhoff/libqalculate-android must be cross compiled, which probably also can be done for ios, but the SWIG wrapper around it currently only generates java code, which is probably not what you want for ios.

I fear it would be best if someone builds a native Qalculate app for ios, sorry
