### ISSUE TITLE
Keep history scrolled to the bottom

### ISSUE THREAD

**Issue by ByteHamster** [jherkenhoff/qalculate-android#53]
The newly added history entries should be visible, not added off-screen at the bottom of the list

**Comment by jherkenhoff** [comment]
Jup, the calculation history handling is still a bit buggy, but I did not thoroughly look into it because I would also like the _current calculation result_ to seamlessly animate into the history list and the _calculation history items_ to have a different look in order to distinguish better from the current calculation result.

**Comment by jherkenhoff** [comment]
Fixed in 6d45cbf7ee2a4995c461137679fdda0bafeafc26
