### ISSUE TITLE
Weird metric suggestions

### ISSUE THREAD

**Issue by notalexnot** [jherkenhoff/qalculate-android#74]
When I write `cm` the suggestions show `cm_c`,  which the calculator interprets as "centimeter × '_' × SpeedOfLight", the same happens with millimeters and kilometers. 

![Screenshot_20241004-181803.png](https://github.com/user-attachments/assets/36220967-639a-4acc-9f59-1197a30524ed)

**Comment by jherkenhoff** [comment]
I have seen these `_c` suggestions before, but at that time the expression was at least interpreted correctly. Not sure when it started interpreting the `c` as speed of light.
I fetch the autocomplete suggestions (and therefore the for example the `cm_c` and `km_c` strings) directly from the upstream qalculate library, and I don't quit get why some units have the _c suffix. I suspect it is because they are "composite" units, but I am not quite sure yet. I will definitely investigate this... Thanks a lot for spotting and reporting!

**Comment by jherkenhoff** [comment]
Fixed in latest release
